package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"gpo/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Supplierreview)
// DB Table: Plural (supplierreviews)
// Resource: Plural (Supplierreviews)
// Path: Plural (/supplierreviews)
// View Template Folder: Plural (/templates/supplierreviews/)

// SupplierreviewsResource is the resource for the Supplierreview model
type SupplierreviewsResource struct {
	buffalo.Resource
}

// List gets all Supplierreviews. This function is mapped to the path
// GET /supplierreviews
func (v SupplierreviewsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	supplierreviews := &models.Supplierreviews{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Supplierreviews from the DB
	if err := q.All(supplierreviews); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("supplierreviews", supplierreviews)
		return c.Render(http.StatusOK, r.HTML("supplierreviews/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(supplierreviews))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(supplierreviews))
	}).Respond(c)
}

// Show gets the data for one Supplierreview. This function is mapped to
// the path GET /supplierreviews/{supplierreview_id}
func (v SupplierreviewsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Supplierreview
	supplierreview := &models.Supplierreview{}

	// To find the Supplierreview the parameter supplierreview_id is used.
	if err := tx.Find(supplierreview, c.Param("supplierreview_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("supplierreview", supplierreview)

		return c.Render(http.StatusOK, r.HTML("supplierreviews/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(supplierreview))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(supplierreview))
	}).Respond(c)
}

// New renders the form for creating a new Supplierreview.
// This function is mapped to the path GET /supplierreviews/new
func (v SupplierreviewsResource) New(c buffalo.Context) error {
	c.Set("supplierreview", &models.Supplierreview{})

	return c.Render(http.StatusOK, r.HTML("supplierreviews/new.plush.html"))
}

// Create adds a Supplierreview to the DB. This function is mapped to the
// path POST /supplierreviews
func (v SupplierreviewsResource) Create(c buffalo.Context) error {
	// Allocate an empty Supplierreview
	supplierreview := &models.Supplierreview{}

	// Bind supplierreview to the html form elements
	if err := c.Bind(supplierreview); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(supplierreview)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("supplierreview", supplierreview)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("supplierreviews/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "supplierreview.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/supplierreviews/%v", supplierreview.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(supplierreview))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(supplierreview))
	}).Respond(c)
}

// Edit renders a edit form for a Supplierreview. This function is
// mapped to the path GET /supplierreviews/{supplierreview_id}/edit
func (v SupplierreviewsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Supplierreview
	supplierreview := &models.Supplierreview{}

	if err := tx.Find(supplierreview, c.Param("supplierreview_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("supplierreview", supplierreview)
	return c.Render(http.StatusOK, r.HTML("supplierreviews/edit.plush.html"))
}

// Update changes a Supplierreview in the DB. This function is mapped to
// the path PUT /supplierreviews/{supplierreview_id}
func (v SupplierreviewsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Supplierreview
	supplierreview := &models.Supplierreview{}

	if err := tx.Find(supplierreview, c.Param("supplierreview_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Supplierreview to the html form elements
	if err := c.Bind(supplierreview); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(supplierreview)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("supplierreview", supplierreview)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("supplierreviews/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "supplierreview.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/supplierreviews/%v", supplierreview.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(supplierreview))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(supplierreview))
	}).Respond(c)
}

// Destroy deletes a Supplierreview from the DB. This function is mapped
// to the path DELETE /supplierreviews/{supplierreview_id}
func (v SupplierreviewsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Supplierreview
	supplierreview := &models.Supplierreview{}

	// To find the Supplierreview the parameter supplierreview_id is used.
	if err := tx.Find(supplierreview, c.Param("supplierreview_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(supplierreview); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "supplierreview.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/supplierreviews")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(supplierreview))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(supplierreview))
	}).Respond(c)
}
