package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"gpo/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Supplier)
// DB Table: Plural (suppliers)
// Resource: Plural (Suppliers)
// Path: Plural (/suppliers)
// View Template Folder: Plural (/templates/suppliers/)

// SuppliersResource is the resource for the Supplier model
type SuppliersResource struct {
	buffalo.Resource
}

// List gets all Suppliers. This function is mapped to the path
// GET /suppliers
func (v SuppliersResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	suppliers := &models.Suppliers{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Suppliers from the DB
	if err := q.All(suppliers); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("suppliers", suppliers)
		return c.Render(http.StatusOK, r.HTML("suppliers/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(suppliers))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(suppliers))
	}).Respond(c)
}

// Show gets the data for one Supplier. This function is mapped to
// the path GET /suppliers/{supplier_id}
func (v SuppliersResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Supplier
	supplier := &models.Supplier{}

	// To find the Supplier the parameter supplier_id is used.
	if err := tx.Find(supplier, c.Param("supplier_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("supplier", supplier)

		return c.Render(http.StatusOK, r.HTML("suppliers/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(supplier))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(supplier))
	}).Respond(c)
}

// New renders the form for creating a new Supplier.
// This function is mapped to the path GET /suppliers/new
func (v SuppliersResource) New(c buffalo.Context) error {
	c.Set("supplier", &models.Supplier{})

	return c.Render(http.StatusOK, r.HTML("suppliers/new.plush.html"))
}

// Create adds a Supplier to the DB. This function is mapped to the
// path POST /suppliers
func (v SuppliersResource) Create(c buffalo.Context) error {
	// Allocate an empty Supplier
	supplier := &models.Supplier{}

	// Bind supplier to the html form elements
	if err := c.Bind(supplier); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(supplier)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("supplier", supplier)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("suppliers/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "supplier.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/suppliers/%v", supplier.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(supplier))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(supplier))
	}).Respond(c)
}

// Edit renders a edit form for a Supplier. This function is
// mapped to the path GET /suppliers/{supplier_id}/edit
func (v SuppliersResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Supplier
	supplier := &models.Supplier{}

	if err := tx.Find(supplier, c.Param("supplier_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("supplier", supplier)
	return c.Render(http.StatusOK, r.HTML("suppliers/edit.plush.html"))
}

// Update changes a Supplier in the DB. This function is mapped to
// the path PUT /suppliers/{supplier_id}
func (v SuppliersResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Supplier
	supplier := &models.Supplier{}

	if err := tx.Find(supplier, c.Param("supplier_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Supplier to the html form elements
	if err := c.Bind(supplier); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(supplier)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("supplier", supplier)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("suppliers/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "supplier.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/suppliers/%v", supplier.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(supplier))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(supplier))
	}).Respond(c)
}

// Destroy deletes a Supplier from the DB. This function is mapped
// to the path DELETE /suppliers/{supplier_id}
func (v SuppliersResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Supplier
	supplier := &models.Supplier{}

	// To find the Supplier the parameter supplier_id is used.
	if err := tx.Find(supplier, c.Param("supplier_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(supplier); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "supplier.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/suppliers")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(supplier))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(supplier))
	}).Respond(c)
}
